### ISSUE TITLE
Disable temporary caching of build number

### ISSUE THREAD

**Issue by simplenotezy** [bartekpacia/fastlane-plugin-get_new_build_number#13]
I find my self having to manually delete the .txt file, if I run multiple builds on my machine while testing. Is this on purpose?

**Comment by bartekpacia** [comment]
Yes, that's on purpose.

Also glad to see I'm not the only one using it! lol

**Comment by simplenotezy** [comment]
I see! Is there a way to disable it? Currently I have to delete the text file manually, after a build have been published to Play Store / App Store, because I need to rerun my lane. Then it will use the cached, old value, instead of fetching the latest from the internet

**Comment by bartekpacia** [comment]
It's not possible, but this sounds like a sensible feature request. PR welcome!

**Comment by simplenotezy** [comment]
I see - will see if I get some time to fix it. Otherwise it'll produce unintended behaviour such as this:

<img width="193" alt="image" src="https://github.com/bartekpacia/fastlane-plugin-get_new_build_number/assets/3786627/8f5d28e5-fb26-417c-96b5-6b781ffb724b">

**Comment by workwithnano** [comment]
#16 addresses this
